# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        opentowork:
            quality: 70
            filters:
                thumbnail:
                    size: [125, 125]
                    mode: outbound
        aboutme:
            quality: 85
            filters:
                thumbnail:
                    size: [380, 514]
                    mode: outbound
        portfolio:
            quality: 70
            filters:
                thumbnail:
                    size: [380, 260]
                    mode: outbound
        portfoliodetail:
            quality: 85
            filters:
                thumbnail:
                    size: [1130, 800]
                    mode: outbound
        posthome:
            quality: 70
            filters:
                thumbnail:
                    size: [320, 200]
                    mode: outbound
        postdetail:
            quality: 85
            filters:
                scale:
                    dim: [450, 290]
                    mode: outbound
        postindex:
            quality: 85
            filters:
                scale:
                    dim: [400, 300]
                    mode: outbound
        user:
            quality: 70
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound
        contact:
            quality: 85
            filters:
                thumbnail:
                    size: [420, 600]
                    mode: outbound
