twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        locales: '%app.locales%'
        site_version: '1.2.2'

when@test:
    twig:
        strict_variables: true
